<?php
namespace CMS;

require_once __DIR__.'/CommentJsonConverter.php';
require_once __DIR__.'/CommentArrayConverter.php';

/**
 * Generated from NGS DSL
 *
 * @property string $URI a unique object identifier (read-only)
 * @property int $ID autogenerated by server (read-only)
 * @property string $content a string
 * @property \NGS\Timestamp $createdAt a timestamp with time zone
 * @property \NGS\Timestamp $modifiedAt a timestamp with time zone
 *
 * @package CMS
 * @version 0.9.9 beta
 */
class Comment extends \NGS\Patterns\AggregateRoot implements \IteratorAggregate
{
    protected $URI;
    protected $ID;
    protected $content;
    protected $createdAt;
    protected $modifiedAt;

    /**
     * Constructs object using a key-property array or instance of class "CMS\Comment"
     *
     * @param array|void $data key-property array or instance of class "CMS\Comment" or pass void to provide all fields with defaults
     */
    public function __construct($data = array(), $construction_type = '')
    {
        if(is_array($data) && $construction_type !== 'build_internal') {
            foreach($data as $key => $val) {
                if(in_array($key, self::$_read_only_properties, true))
                    throw new \LogicException($key.' is a read only property and can\'t be set through the constructor.');
            }
        }
        if (is_array($data)) {
            $this->fromArray($data);
        } else {
            throw new \InvalidArgumentException('Constructor parameter must be an array! Type was: '.\NGS\Utils::getType($data));
        }
    }

    /**
     * Supply default values for uninitialized properties
     *
     * @param array $data key-property array which will be filled in-place
     */
    private static function provideDefaults(array &$data)
    {
        if(!array_key_exists('URI', $data))
            $data['URI'] = null; //a string representing a unique object identifier
        if(!array_key_exists('ID', $data))
            $data['ID'] = 0; // an integer number
        if(!array_key_exists('content', $data))
            $data['content'] = ''; // a string
        if(!array_key_exists('createdAt', $data))
            $data['createdAt'] = new \NGS\Timestamp(); // a timestamp with time zone
        if(!array_key_exists('modifiedAt', $data))
            $data['modifiedAt'] = new \NGS\Timestamp(); // a timestamp with time zone
    }

    /**
     * Constructs object from a key-property array
     *
     * @param array $data key-property array
     */
    private function fromArray(array $data)
    {
        $this->provideDefaults($data);

        if(isset($data['URI']))
            $this->URI = \NGS\Converter\PrimitiveConverter::toString($data['URI']);
        unset($data['URI']);
        if (array_key_exists('ID', $data))
            $this->setID($data['ID']);
        unset($data['ID']);
        if (array_key_exists('content', $data))
            $this->setContent($data['content']);
        unset($data['content']);
        if (array_key_exists('createdAt', $data))
            $this->setCreatedAt($data['createdAt']);
        unset($data['createdAt']);
        if (array_key_exists('modifiedAt', $data))
            $this->setModifiedAt($data['modifiedAt']);
        unset($data['modifiedAt']);

        if (count($data) !== 0 && \NGS\Utils::WarningsAsErrors())
            throw new \InvalidArgumentException('Superflous array keys found in "CMS\Comment" constructor: '.implode(', ', array_keys($data)));
    }

// ============================================================================

    /**
     * Helper getter function, body for magic method $this->__get('URI')
     * URI is a string representation of the primary key.
     *
     * @return string unique resource identifier representing this object
     */
    public function getURI()
    {
        return $this->URI;
    }

    /**
     * @return an integer number
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * @return a string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * @return a timestamp with time zone
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @return a timestamp with time zone
     */
    public function getModifiedAt()
    {
        return $this->modifiedAt;
    }

    /**
     * Property getter which throws Exceptions on invalid access
     *
     * @param string $name Property name
     *
     * @return mixed
     */
    public function __get($name)
    {
        if ($name === 'URI')
            return $this->getURI(); // a string representing a unique object identifier
        if ($name === 'ID')
            return $this->getID(); // an integer number
        if ($name === 'content')
            return $this->getContent(); // a string
        if ($name === 'createdAt')
            return $this->getCreatedAt(); // a timestamp with time zone
        if ($name === 'modifiedAt')
            return $this->getModifiedAt(); // a timestamp with time zone

        throw new \InvalidArgumentException('Property "'.$name.'" in class "CMS\Comment" does not exist and could not be retrieved!');
    }

// ============================================================================

    /**
     * Property existence checker
     *
     * @param string $name Property name to check for existence
     *
     * @return bool will return true if and only if the propery exist and is not null
     */
    public function __isset($name)
    {
        if ($name === 'URI')
            return $this->URI !== null;
        if ($name === 'content')
            return true; // a string (always set)
        if ($name === 'createdAt')
            return true; // a timestamp with time zone (always set)
        if ($name === 'modifiedAt')
            return true; // a timestamp with time zone (always set)

        return false;
    }

    private static $_read_only_properties = array('URI', 'ID');

    /**
     * @param int $value an integer number
     *
     * @return int
     */
    private function setID($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "ID" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toInteger($value);
        $this->ID = $value;
        return $value;
    }

    /**
     * @param string $value a string
     *
     * @return string
     */
    public function setContent($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "content" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toString($value);
        $this->content = $value;
        return $value;
    }

    /**
     * @param \NGS\Timestamp $value a timestamp with time zone
     *
     * @return \NGS\Timestamp
     */
    public function setCreatedAt($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "createdAt" cannot be set to null because it is non-nullable!');
        $value = new \NGS\Timestamp($value);
        $this->createdAt = $value;
        return $value;
    }

    /**
     * @param \NGS\Timestamp $value a timestamp with time zone
     *
     * @return \NGS\Timestamp
     */
    public function setModifiedAt($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "modifiedAt" cannot be set to null because it is non-nullable!');
        $value = new \NGS\Timestamp($value);
        $this->modifiedAt = $value;
        return $value;
    }

    /**
     * Property setter which checks for invalid access to entity properties and enforces proper type checks
     *
     * @param string $name Property name
     * @param mixed $value Property value
     */
    public function __set($name, $value)
    {
        if(in_array($name, self::$_read_only_properties, true))
            throw new \LogicException('Property "'.$name.'" in "CMS\Comment" cannot be set, because it is read-only!');
        if ($name === 'content')
            return $this->setContent($value); // a string
        if ($name === 'createdAt')
            return $this->setCreatedAt($value); // a timestamp with time zone
        if ($name === 'modifiedAt')
            return $this->setModifiedAt($value); // a timestamp with time zone
        throw new \InvalidArgumentException('Property "'.$name.'" in class "CMS\Comment" does not exist and could not be set!');
    }

    /**
     * Will unset a property if it exists, but throw an exception if it is not nullable
     *
     * @param string $name Property name to unset (set to null)
     */
    public function __unset($name)
    {
        if(in_array($name, self::$_read_only_properties, true))
            throw new \LogicException('Property "'.$name.'" cannot be unset, because it is read-only!');
        if ($name === 'content')
            throw new \LogicException('The property "content" cannot be unset because it is non-nullable!'); // a string (cannot be unset)
        if ($name === 'createdAt')
            throw new \LogicException('The property "createdAt" cannot be unset because it is non-nullable!'); // a timestamp with time zone (cannot be unset)
        if ($name === 'modifiedAt')
            throw new \LogicException('The property "modifiedAt" cannot be unset because it is non-nullable!'); // a timestamp with time zone (cannot be unset)
    }

    /**
     * Create or update CMS\Comment instance (server call)
     *
     * @return modified instance object
     */
    public function persist()
    {

        $newObject = parent::persist();
        $this->updateWithAnother($newObject);

        return $this;
    }

    private function updateWithAnother(\CMS\Comment $result)
    {
        $this->URI = $result->URI;

        $this->content = $result->content;
        $this->createdAt = $result->createdAt;
        $this->modifiedAt = $result->modifiedAt;
        $this->ID = $result->ID;
    }

    public function toJson()
    {
        return \CMS\CommentJsonConverter::toJson($this);
    }

    public static function fromJson($item)
    {
        return \CMS\CommentJsonConverter::fromJson($item);
    }

    public function __toString()
    {
        return 'CMS\Comment'.$this->toJson();
    }

    public function __clone()
    {
        return \CMS\CommentArrayConverter::fromArray(\CMS\CommentArrayConverter::toArray($this));
    }

    public function toArray()
    {
        return \CMS\CommentArrayConverter::toArray($this);
    }

    /**
     * Implementation of the IteratorAggregate interface via \ArrayIterator
     *
     * @return Traversable a new iterator specially created for this iteratation
     */
    public function getIterator()
    {
        return new \ArrayIterator(\CMS\CommentArrayConverter::toArray($this));
    }
}