<?php
namespace Football;

require_once __DIR__.'/PlayerJsonConverter.php';
require_once __DIR__.'/PlayerArrayConverter.php';
require_once __DIR__.'/Team.php';

/**
 * Generated from NGS DSL
 *
 * @property string $URI a unique object identifier (read-only)
 * @property int $ID autogenerated by server (read-only)
 * @property string $name a string
 * @property int $teamID used by reference $team (read-only)
 * @property string $teamURI reference to an object of class "Football\Team" (read-only)
 * @property \Football\Team $team an object of class "Football\Team"
 *
 * @package Football
 * @version 0.9.9 beta
 */
class Player extends \NGS\Patterns\AggregateRoot implements \IteratorAggregate
{
    protected $URI;
    protected $ID;
    protected $name;
    protected $teamID;
    protected $teamURI;
    protected $team;

    /**
     * Constructs object using a key-property array or instance of class "Football\Player"
     *
     * @param array|void $data key-property array or instance of class "Football\Player" or pass void to provide all fields with defaults
     */
    public function __construct($data = array(), $construction_type = '')
    {
        if(is_array($data) && $construction_type !== 'build_internal') {
            foreach($data as $key => $val) {
                if(in_array($key, self::$_read_only_properties, true))
                    throw new \LogicException($key.' is a read only property and can\'t be set through the constructor.');
            }
        }
        if (is_array($data)) {
            $this->fromArray($data);
        } else {
            throw new \InvalidArgumentException('Constructor parameter must be an array! Type was: '.\NGS\Utils::getType($data));
        }
    }

    /**
     * Supply default values for uninitialized properties
     *
     * @param array $data key-property array which will be filled in-place
     */
    private static function provideDefaults(array &$data)
    {
        if(!array_key_exists('URI', $data))
            $data['URI'] = null; //a string representing a unique object identifier
        if(!array_key_exists('ID', $data))
            $data['ID'] = 0; // an integer number
        if(!array_key_exists('name', $data))
            $data['name'] = ''; // a string
        if(!array_key_exists('teamID', $data))
            $data['teamID'] = 0; // an integer number
    }

    /**
     * Constructs object from a key-property array
     *
     * @param array $data key-property array
     */
    private function fromArray(array $data)
    {
        $this->provideDefaults($data);

        if(isset($data['URI']))
            $this->URI = \NGS\Converter\PrimitiveConverter::toString($data['URI']);
        unset($data['URI']);
        if (array_key_exists('ID', $data))
            $this->setID($data['ID']);
        unset($data['ID']);
        if (array_key_exists('name', $data))
            $this->setName($data['name']);
        unset($data['name']);
        if (array_key_exists('teamID', $data))
            $this->setTeamID($data['teamID']);
        unset($data['teamID']);
        if (array_key_exists('team', $data))
            $this->setTeam($data['team']);
        unset($data['team']);
        if(array_key_exists('teamURI', $data))
            $this->teamURI = \NGS\Converter\PrimitiveConverter::toString($data['teamURI']);
        unset($data['teamURI']);

        if (count($data) !== 0 && \NGS\Utils::WarningsAsErrors())
            throw new \InvalidArgumentException('Superflous array keys found in "Football\Player" constructor: '.implode(', ', array_keys($data)));
    }

// ============================================================================

    /**
     * Helper getter function, body for magic method $this->__get('URI')
     * URI is a string representation of the primary key.
     *
     * @return string unique resource identifier representing this object
     */
    public function getURI()
    {
        return $this->URI;
    }

    /**
     * @return an integer number
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * @return a string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @return an integer number
     */
    public function getTeamID()
    {
        return $this->teamID;
    }

    /**
     * @return a reference to an object of class "Football\Team"
     */
    public function getTeamURI()
    {
        return $this->teamURI;
    }

    /**
     * @return an object of class "Football\Team"
     */
    public function getTeam()
    {
        if ($this->teamURI !== null && $this->team === null)
            $this->team = \NGS\Patterns\Repository::instance()->find('Football\\Team', $this->teamURI);
        return $this->team;
    }

    /**
     * Property getter which throws Exceptions on invalid access
     *
     * @param string $name Property name
     *
     * @return mixed
     */
    public function __get($name)
    {
        if ($name === 'URI')
            return $this->getURI(); // a string representing a unique object identifier
        if ($name === 'ID')
            return $this->getID(); // an integer number
        if ($name === 'name')
            return $this->getName(); // a string
        if ($name === 'teamID')
            return $this->getTeamID(); // an integer number
        if ($name === 'teamURI')
            return $this->getTeamURI(); // a reference to an object of class "Football\Team"
        if ($name === 'team')
            return $this->getTeam(); // an object of class "Football\Team"

        throw new \InvalidArgumentException('Property "'.$name.'" in class "Football\Player" does not exist and could not be retrieved!');
    }

// ============================================================================

    /**
     * Property existence checker
     *
     * @param string $name Property name to check for existence
     *
     * @return bool will return true if and only if the propery exist and is not null
     */
    public function __isset($name)
    {
        if ($name === 'URI')
            return $this->URI !== null;
        if ($name === 'name')
            return true; // a string (always set)
        if ($name === 'team')
            return true; // an object of class "Football\Team" (always set)

        return false;
    }

    private static $_read_only_properties = array('URI', 'ID', 'teamID', 'teamURI');

    /**
     * @param int $value an integer number
     *
     * @return int
     */
    private function setID($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "ID" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toInteger($value);
        $this->ID = $value;
        return $value;
    }

    /**
     * @param string $value a string
     *
     * @return string
     */
    public function setName($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "name" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toString($value);
        $this->name = $value;
        return $value;
    }

    /**
     * @param int $value an integer number
     *
     * @return int
     */
    private function setTeamID($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "teamID" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toInteger($value);
        $this->teamID = $value;
        return $value;
    }

    /**
     * @param \Football\Team $value an object of class "Football\Team"
     *
     * @return \Football\Team
     */
    public function setTeam($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "team" cannot be set to null because it is non-nullable!');
        $value = \Football\TeamArrayConverter::fromArray($value);
        if ($value->URI === null)
            throw new \InvalidArgumentException('Value of property "team" cannot have URI set to null because it\'s a reference! Reference values must have non-null URIs!');
        $this->team = $value;
        $this->teamURI = $value->URI;
        $this->teamID = $value->ID;
        return $value;
    }

    /**
     * Property setter which checks for invalid access to entity properties and enforces proper type checks
     *
     * @param string $name Property name
     * @param mixed $value Property value
     */
    public function __set($name, $value)
    {
        if(in_array($name, self::$_read_only_properties, true))
            throw new \LogicException('Property "'.$name.'" in "Football\Player" cannot be set, because it is read-only!');
        if ($name === 'name')
            return $this->setName($value); // a string
        if ($name === 'team')
            return $this->setTeam($value); // an object of class "Football\Team"
        throw new \InvalidArgumentException('Property "'.$name.'" in class "Football\Player" does not exist and could not be set!');
    }

    /**
     * Will unset a property if it exists, but throw an exception if it is not nullable
     *
     * @param string $name Property name to unset (set to null)
     */
    public function __unset($name)
    {
        if(in_array($name, self::$_read_only_properties, true))
            throw new \LogicException('Property "'.$name.'" cannot be unset, because it is read-only!');
        if ($name === 'name')
            throw new \LogicException('The property "name" cannot be unset because it is non-nullable!'); // a string (cannot be unset)
        if ($name === 'team')
            throw new \LogicException('The property "team" cannot be unset because it is non-nullable!'); // an object of class "Football\Team" (cannot be unset)
    }

    /**
     * Create or update Football\Player instance (server call)
     *
     * @return modified instance object
     */
    public function persist()
    {

        if ($this->teamURI === null && $this->teamID !== null) {
            throw new \LogicException('Cannot persist instance of "Football\Player" because reference "team" was not assigned');
        }
        $newObject = parent::persist();
        $this->updateWithAnother($newObject);

        return $this;
    }

    private function updateWithAnother(\Football\Player $result)
    {
        $this->URI = $result->URI;

        $this->name = $result->name;
        $this->teamID = $result->teamID;
        $this->team = $result->team;
        $this->teamURI = $result->teamURI;
        $this->ID = $result->ID;
    }

    public function toJson()
    {
        return \Football\PlayerJsonConverter::toJson($this);
    }

    public static function fromJson($item)
    {
        return \Football\PlayerJsonConverter::fromJson($item);
    }

    public function __toString()
    {
        return 'Football\Player'.$this->toJson();
    }

    public function __clone()
    {
        return \Football\PlayerArrayConverter::fromArray(\Football\PlayerArrayConverter::toArray($this));
    }

    public function toArray()
    {
        return \Football\PlayerArrayConverter::toArray($this);
    }

    /**
     * Implementation of the IteratorAggregate interface via \ArrayIterator
     *
     * @return Traversable a new iterator specially created for this iteratation
     */
    public function getIterator()
    {
        return new \ArrayIterator(\Football\PlayerArrayConverter::toArray($this));
    }
}