<?php
namespace Todo;

require_once __DIR__.'/TaskJsonConverter.php';
require_once __DIR__.'/TaskArrayConverter.php';

/**
 * Generated from NGS DSL
 *
 * @property string $URI a unique object identifier (read-only)
 * @property int $ID autogenerated by server (read-only)
 * @property string $name a string
 * @property int $priority an integer number
 * @property bool $isDone a boolean value
 * @property \NGS\Timestamp $created a timestamp with time zone
 *
 * @package Todo
 * @version 0.9.9 beta
 */
class Task extends \NGS\Patterns\AggregateRoot implements \IteratorAggregate
{
    protected $URI;
    protected $ID;
    protected $name;
    protected $priority;
    protected $isDone;
    protected $created;

    /**
     * Constructs object using a key-property array or instance of class "Todo\Task"
     *
     * @param array|void $data key-property array or instance of class "Todo\Task" or pass void to provide all fields with defaults
     */
    public function __construct($data = array(), $construction_type = '')
    {
        if(is_array($data) && $construction_type !== 'build_internal') {
            foreach($data as $key => $val) {
                if(in_array($key, self::$_read_only_properties, true))
                    throw new \LogicException($key.' is a read only property and can\'t be set through the constructor.');
            }
        }
        if (is_array($data)) {
            $this->fromArray($data);
        } else {
            throw new \InvalidArgumentException('Constructor parameter must be an array! Type was: '.\NGS\Utils::getType($data));
        }
    }

    /**
     * Supply default values for uninitialized properties
     *
     * @param array $data key-property array which will be filled in-place
     */
    private static function provideDefaults(array &$data)
    {
        if(!array_key_exists('URI', $data))
            $data['URI'] = null; //a string representing a unique object identifier
        if(!array_key_exists('ID', $data))
            $data['ID'] = 0; // an integer number
        if(!array_key_exists('name', $data))
            $data['name'] = ''; // a string
        if(!array_key_exists('priority', $data))
            $data['priority'] = 0; // an integer number
        if(!array_key_exists('isDone', $data))
            $data['isDone'] = false; // a boolean value
        if(!array_key_exists('created', $data))
            $data['created'] = new \NGS\Timestamp(); // a timestamp with time zone
    }

    /**
     * Constructs object from a key-property array
     *
     * @param array $data key-property array
     */
    private function fromArray(array $data)
    {
        $this->provideDefaults($data);

        if(isset($data['URI']))
            $this->URI = \NGS\Converter\PrimitiveConverter::toString($data['URI']);
        unset($data['URI']);
        if (array_key_exists('ID', $data))
            $this->setID($data['ID']);
        unset($data['ID']);
        if (array_key_exists('name', $data))
            $this->setName($data['name']);
        unset($data['name']);
        if (array_key_exists('priority', $data))
            $this->setPriority($data['priority']);
        unset($data['priority']);
        if (array_key_exists('isDone', $data))
            $this->setIsDone($data['isDone']);
        unset($data['isDone']);
        if (array_key_exists('created', $data))
            $this->setCreated($data['created']);
        unset($data['created']);

        if (count($data) !== 0 && \NGS\Utils::WarningsAsErrors())
            throw new \InvalidArgumentException('Superflous array keys found in "Todo\Task" constructor: '.implode(', ', array_keys($data)));
    }

// ============================================================================

    /**
     * Helper getter function, body for magic method $this->__get('URI')
     * URI is a string representation of the primary key.
     *
     * @return string unique resource identifier representing this object
     */
    public function getURI()
    {
        return $this->URI;
    }

    /**
     * @return an integer number
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * @return a string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @return an integer number
     */
    public function getPriority()
    {
        return $this->priority;
    }

    /**
     * @return a boolean value
     */
    public function getIsDone()
    {
        return $this->isDone;
    }

    /**
     * @return a timestamp with time zone
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Property getter which throws Exceptions on invalid access
     *
     * @param string $name Property name
     *
     * @return mixed
     */
    public function __get($name)
    {
        if ($name === 'URI')
            return $this->getURI(); // a string representing a unique object identifier
        if ($name === 'ID')
            return $this->getID(); // an integer number
        if ($name === 'name')
            return $this->getName(); // a string
        if ($name === 'priority')
            return $this->getPriority(); // an integer number
        if ($name === 'isDone')
            return $this->getIsDone(); // a boolean value
        if ($name === 'created')
            return $this->getCreated(); // a timestamp with time zone

        throw new \InvalidArgumentException('Property "'.$name.'" in class "Todo\Task" does not exist and could not be retrieved!');
    }

// ============================================================================

    /**
     * Property existence checker
     *
     * @param string $name Property name to check for existence
     *
     * @return bool will return true if and only if the propery exist and is not null
     */
    public function __isset($name)
    {
        if ($name === 'URI')
            return $this->URI !== null;
        if ($name === 'name')
            return true; // a string (always set)
        if ($name === 'priority')
            return true; // an integer number (always set)
        if ($name === 'isDone')
            return true; // a boolean value (always set)
        if ($name === 'created')
            return true; // a timestamp with time zone (always set)

        return false;
    }

    private static $_read_only_properties = array('URI', 'ID');

    /**
     * @param int $value an integer number
     *
     * @return int
     */
    private function setID($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "ID" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toInteger($value);
        $this->ID = $value;
        return $value;
    }

    /**
     * @param string $value a string
     *
     * @return string
     */
    public function setName($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "name" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toString($value);
        $this->name = $value;
        return $value;
    }

    /**
     * @param int $value an integer number
     *
     * @return int
     */
    public function setPriority($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "priority" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toInteger($value);
        $this->priority = $value;
        return $value;
    }

    /**
     * @param bool $value a boolean value
     *
     * @return bool
     */
    public function setIsDone($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "isDone" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toBoolean($value);
        $this->isDone = $value;
        return $value;
    }

    /**
     * @param \NGS\Timestamp $value a timestamp with time zone
     *
     * @return \NGS\Timestamp
     */
    public function setCreated($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "created" cannot be set to null because it is non-nullable!');
        $value = new \NGS\Timestamp($value);
        $this->created = $value;
        return $value;
    }

    /**
     * Property setter which checks for invalid access to entity properties and enforces proper type checks
     *
     * @param string $name Property name
     * @param mixed $value Property value
     */
    public function __set($name, $value)
    {
        if(in_array($name, self::$_read_only_properties, true))
            throw new \LogicException('Property "'.$name.'" in "Todo\Task" cannot be set, because it is read-only!');
        if ($name === 'name')
            return $this->setName($value); // a string
        if ($name === 'priority')
            return $this->setPriority($value); // an integer number
        if ($name === 'isDone')
            return $this->setIsDone($value); // a boolean value
        if ($name === 'created')
            return $this->setCreated($value); // a timestamp with time zone
        throw new \InvalidArgumentException('Property "'.$name.'" in class "Todo\Task" does not exist and could not be set!');
    }

    /**
     * Will unset a property if it exists, but throw an exception if it is not nullable
     *
     * @param string $name Property name to unset (set to null)
     */
    public function __unset($name)
    {
        if(in_array($name, self::$_read_only_properties, true))
            throw new \LogicException('Property "'.$name.'" cannot be unset, because it is read-only!');
        if ($name === 'name')
            throw new \LogicException('The property "name" cannot be unset because it is non-nullable!'); // a string (cannot be unset)
        if ($name === 'priority')
            throw new \LogicException('The property "priority" cannot be unset because it is non-nullable!'); // an integer number (cannot be unset)
        if ($name === 'isDone')
            throw new \LogicException('The property "isDone" cannot be unset because it is non-nullable!'); // a boolean value (cannot be unset)
        if ($name === 'created')
            throw new \LogicException('The property "created" cannot be unset because it is non-nullable!'); // a timestamp with time zone (cannot be unset)
    }

    /**
     * Create or update Todo\Task instance (server call)
     *
     * @return modified instance object
     */
    public function persist()
    {

        $newObject = parent::persist();
        $this->updateWithAnother($newObject);

        return $this;
    }

    private function updateWithAnother(\Todo\Task $result)
    {
        $this->URI = $result->URI;

        $this->name = $result->name;
        $this->priority = $result->priority;
        $this->isDone = $result->isDone;
        $this->created = $result->created;
        $this->ID = $result->ID;
    }

    public function toJson()
    {
        return \Todo\TaskJsonConverter::toJson($this);
    }

    public static function fromJson($item)
    {
        return \Todo\TaskJsonConverter::fromJson($item);
    }

    public function __toString()
    {
        return 'Todo\Task'.$this->toJson();
    }

    public function __clone()
    {
        return \Todo\TaskArrayConverter::fromArray(\Todo\TaskArrayConverter::toArray($this));
    }

    public function toArray()
    {
        return \Todo\TaskArrayConverter::toArray($this);
    }

    /**
     * Implementation of the IteratorAggregate interface via \ArrayIterator
     *
     * @return Traversable a new iterator specially created for this iteratation
     */
    public function getIterator()
    {
        return new \ArrayIterator(\Todo\TaskArrayConverter::toArray($this));
    }

    /**
     * Find data using declared specification findDone
     * Search can be limited by $searchLimit and $searchOffset integer arguments
     *
     * @return array of objects that satisfy specification
     */
    public static function findDone($searchLimit = null, $searchOffset = null)
    {
        require_once __DIR__.'/Task/findDone.php';
        $specification = new \Todo\Task\findDone();
        return $specification->search($searchLimit, $searchOffset);
    }

    /**
     * Find data using declared specification findByName
     * Search can be limited by $searchLimit and $searchOffset integer arguments
     *
     * @return array of objects that satisfy specification
     */
    public static function findByName($query, $searchLimit = null, $searchOffset = null)
    {
        require_once __DIR__.'/Task/findByName.php';
        $specification = new \Todo\Task\findByName(array('query' => $query));
        return $specification->search($searchLimit, $searchOffset);
    }

    /**
     * Find data using declared specification findRecent
     * Search can be limited by $searchLimit and $searchOffset integer arguments
     *
     * @return array of objects that satisfy specification
     */
    public static function findRecent($days, $minPriority, $maxPriority, $searchLimit = null, $searchOffset = null)
    {
        require_once __DIR__.'/Task/findRecent.php';
        $specification = new \Todo\Task\findRecent(array('days' => $days, 'minPriority' => $minPriority, 'maxPriority' => $maxPriority));
        return $specification->search($searchLimit, $searchOffset);
    }
}