<?php
namespace ERP;

require_once __DIR__.'/ConversionRateJsonConverter.php';
require_once __DIR__.'/ConversionRateArrayConverter.php';

/**
 * Generated from NGS DSL
 *
 * @property string $URI a unique object identifier (read-only)
 * @property int $ID autogenerated by server (read-only)
 * @property string $from a string
 * @property string $to a string
 * @property float $rate a floating point number
 *
 * @package ERP
 * @version 0.9.9 beta
 */
class ConversionRate extends \NGS\Patterns\AggregateRoot implements \IteratorAggregate
{
    protected $URI;
    protected $ID;
    protected $from;
    protected $to;
    protected $rate;

    /**
     * Constructs object using a key-property array or instance of class "ERP\ConversionRate"
     *
     * @param array|void $data key-property array or instance of class "ERP\ConversionRate" or pass void to provide all fields with defaults
     */
    public function __construct($data = array(), $construction_type = '')
    {
        if(is_array($data) && $construction_type !== 'build_internal') {
            foreach($data as $key => $val) {
                if(in_array($key, self::$_read_only_properties, true))
                    throw new \LogicException($key.' is a read only property and can\'t be set through the constructor.');
            }
        }
        if (is_array($data)) {
            $this->fromArray($data);
        } else {
            throw new \InvalidArgumentException('Constructor parameter must be an array! Type was: '.\NGS\Utils::getType($data));
        }
    }

    /**
     * Supply default values for uninitialized properties
     *
     * @param array $data key-property array which will be filled in-place
     */
    private static function provideDefaults(array &$data)
    {
        if(!array_key_exists('URI', $data))
            $data['URI'] = null; //a string representing a unique object identifier
        if(!array_key_exists('ID', $data))
            $data['ID'] = 0; // an integer number
        if(!array_key_exists('from', $data))
            $data['from'] = ''; // a string
        if(!array_key_exists('to', $data))
            $data['to'] = ''; // a string
        if(!array_key_exists('rate', $data))
            $data['rate'] = 0.; // a floating point number
    }

    /**
     * Constructs object from a key-property array
     *
     * @param array $data key-property array
     */
    private function fromArray(array $data)
    {
        $this->provideDefaults($data);

        if(isset($data['URI']))
            $this->URI = \NGS\Converter\PrimitiveConverter::toString($data['URI']);
        unset($data['URI']);
        if (array_key_exists('ID', $data))
            $this->setID($data['ID']);
        unset($data['ID']);
        if (array_key_exists('from', $data))
            $this->setFrom($data['from']);
        unset($data['from']);
        if (array_key_exists('to', $data))
            $this->setTo($data['to']);
        unset($data['to']);
        if (array_key_exists('rate', $data))
            $this->setRate($data['rate']);
        unset($data['rate']);

        if (count($data) !== 0 && \NGS\Utils::WarningsAsErrors())
            throw new \InvalidArgumentException('Superflous array keys found in "ERP\ConversionRate" constructor: '.implode(', ', array_keys($data)));
    }

// ============================================================================

    /**
     * Helper getter function, body for magic method $this->__get('URI')
     * URI is a string representation of the primary key.
     *
     * @return string unique resource identifier representing this object
     */
    public function getURI()
    {
        return $this->URI;
    }

    /**
     * @return an integer number
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * @return a string
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     * @return a string
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     * @return a floating point number
     */
    public function getRate()
    {
        return $this->rate;
    }

    /**
     * Property getter which throws Exceptions on invalid access
     *
     * @param string $name Property name
     *
     * @return mixed
     */
    public function __get($name)
    {
        if ($name === 'URI')
            return $this->getURI(); // a string representing a unique object identifier
        if ($name === 'ID')
            return $this->getID(); // an integer number
        if ($name === 'from')
            return $this->getFrom(); // a string
        if ($name === 'to')
            return $this->getTo(); // a string
        if ($name === 'rate')
            return $this->getRate(); // a floating point number

        throw new \InvalidArgumentException('Property "'.$name.'" in class "ERP\ConversionRate" does not exist and could not be retrieved!');
    }

// ============================================================================

    /**
     * Property existence checker
     *
     * @param string $name Property name to check for existence
     *
     * @return bool will return true if and only if the propery exist and is not null
     */
    public function __isset($name)
    {
        if ($name === 'URI')
            return $this->URI !== null;
        if ($name === 'from')
            return true; // a string (always set)
        if ($name === 'to')
            return true; // a string (always set)
        if ($name === 'rate')
            return true; // a floating point number (always set)

        return false;
    }

    private static $_read_only_properties = array('URI', 'ID');

    /**
     * @param int $value an integer number
     *
     * @return int
     */
    private function setID($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "ID" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toInteger($value);
        $this->ID = $value;
        return $value;
    }

    /**
     * @param string $value a string
     *
     * @return string
     */
    public function setFrom($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "from" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toString($value);
        $this->from = $value;
        return $value;
    }

    /**
     * @param string $value a string
     *
     * @return string
     */
    public function setTo($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "to" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toString($value);
        $this->to = $value;
        return $value;
    }

    /**
     * @param float $value a floating point number
     *
     * @return float
     */
    public function setRate($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "rate" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toFloat($value);
        $this->rate = $value;
        return $value;
    }

    /**
     * Property setter which checks for invalid access to entity properties and enforces proper type checks
     *
     * @param string $name Property name
     * @param mixed $value Property value
     */
    public function __set($name, $value)
    {
        if(in_array($name, self::$_read_only_properties, true))
            throw new \LogicException('Property "'.$name.'" in "ERP\ConversionRate" cannot be set, because it is read-only!');
        if ($name === 'from')
            return $this->setFrom($value); // a string
        if ($name === 'to')
            return $this->setTo($value); // a string
        if ($name === 'rate')
            return $this->setRate($value); // a floating point number
        throw new \InvalidArgumentException('Property "'.$name.'" in class "ERP\ConversionRate" does not exist and could not be set!');
    }

    /**
     * Will unset a property if it exists, but throw an exception if it is not nullable
     *
     * @param string $name Property name to unset (set to null)
     */
    public function __unset($name)
    {
        if(in_array($name, self::$_read_only_properties, true))
            throw new \LogicException('Property "'.$name.'" cannot be unset, because it is read-only!');
        if ($name === 'from')
            throw new \LogicException('The property "from" cannot be unset because it is non-nullable!'); // a string (cannot be unset)
        if ($name === 'to')
            throw new \LogicException('The property "to" cannot be unset because it is non-nullable!'); // a string (cannot be unset)
        if ($name === 'rate')
            throw new \LogicException('The property "rate" cannot be unset because it is non-nullable!'); // a floating point number (cannot be unset)
    }

    /**
     * Create or update ERP\ConversionRate instance (server call)
     *
     * @return modified instance object
     */
    public function persist()
    {

        $newObject = parent::persist();
        $this->updateWithAnother($newObject);

        return $this;
    }

    private function updateWithAnother(\ERP\ConversionRate $result)
    {
        $this->URI = $result->URI;

        $this->from = $result->from;
        $this->to = $result->to;
        $this->rate = $result->rate;
        $this->ID = $result->ID;
    }

    public function toJson()
    {
        return \ERP\ConversionRateJsonConverter::toJson($this);
    }

    public static function fromJson($item)
    {
        return \ERP\ConversionRateJsonConverter::fromJson($item);
    }

    public function __toString()
    {
        return 'ERP\ConversionRate'.$this->toJson();
    }

    public function __clone()
    {
        return \ERP\ConversionRateArrayConverter::fromArray(\ERP\ConversionRateArrayConverter::toArray($this));
    }

    public function toArray()
    {
        return \ERP\ConversionRateArrayConverter::toArray($this);
    }

    /**
     * Implementation of the IteratorAggregate interface via \ArrayIterator
     *
     * @return Traversable a new iterator specially created for this iteratation
     */
    public function getIterator()
    {
        return new \ArrayIterator(\ERP\ConversionRateArrayConverter::toArray($this));
    }
}