<?php
namespace ERP;

require_once __DIR__.'/ProductJsonConverter.php';
require_once __DIR__.'/ProductArrayConverter.php';

/**
 * Generated from NGS DSL
 *
 * @property string $URI a unique object identifier (read-only)
 * @property int $ID autogenerated by server (read-only)
 * @property string $name a string
 * @property string $description a string
 * @property \NGS\Money $price a money amount
 *
 * @package ERP
 * @version 0.9.9 beta
 */
class Product extends \NGS\Patterns\AggregateRoot implements \IteratorAggregate
{
    protected $URI;
    protected $ID;
    protected $name;
    protected $description;
    protected $price;

    /**
     * Constructs object using a key-property array or instance of class "ERP\Product"
     *
     * @param array|void $data key-property array or instance of class "ERP\Product" or pass void to provide all fields with defaults
     */
    public function __construct($data = array(), $construction_type = '')
    {
        if(is_array($data) && $construction_type !== 'build_internal') {
            foreach($data as $key => $val) {
                if(in_array($key, self::$_read_only_properties, true))
                    throw new \LogicException($key.' is a read only property and can\'t be set through the constructor.');
            }
        }
        if (is_array($data)) {
            $this->fromArray($data);
        } else {
            throw new \InvalidArgumentException('Constructor parameter must be an array! Type was: '.\NGS\Utils::getType($data));
        }
    }

    /**
     * Supply default values for uninitialized properties
     *
     * @param array $data key-property array which will be filled in-place
     */
    private static function provideDefaults(array &$data)
    {
        if(!array_key_exists('URI', $data))
            $data['URI'] = null; //a string representing a unique object identifier
        if(!array_key_exists('ID', $data))
            $data['ID'] = 0; // an integer number
        if(!array_key_exists('name', $data))
            $data['name'] = ''; // a string
        if(!array_key_exists('description', $data))
            $data['description'] = ''; // a string
        if(!array_key_exists('price', $data))
            $data['price'] = new \NGS\Money(0); // a money amount
    }

    /**
     * Constructs object from a key-property array
     *
     * @param array $data key-property array
     */
    private function fromArray(array $data)
    {
        $this->provideDefaults($data);

        if(isset($data['URI']))
            $this->URI = \NGS\Converter\PrimitiveConverter::toString($data['URI']);
        unset($data['URI']);
        if (array_key_exists('ID', $data))
            $this->setID($data['ID']);
        unset($data['ID']);
        if (array_key_exists('name', $data))
            $this->setName($data['name']);
        unset($data['name']);
        if (array_key_exists('description', $data))
            $this->setDescription($data['description']);
        unset($data['description']);
        if (array_key_exists('price', $data))
            $this->setPrice($data['price']);
        unset($data['price']);

        if (count($data) !== 0 && \NGS\Utils::WarningsAsErrors())
            throw new \InvalidArgumentException('Superflous array keys found in "ERP\Product" constructor: '.implode(', ', array_keys($data)));
    }

// ============================================================================

    /**
     * Helper getter function, body for magic method $this->__get('URI')
     * URI is a string representation of the primary key.
     *
     * @return string unique resource identifier representing this object
     */
    public function getURI()
    {
        return $this->URI;
    }

    /**
     * @return an integer number
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * @return a string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @return a string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @return a money amount
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Property getter which throws Exceptions on invalid access
     *
     * @param string $name Property name
     *
     * @return mixed
     */
    public function __get($name)
    {
        if ($name === 'URI')
            return $this->getURI(); // a string representing a unique object identifier
        if ($name === 'ID')
            return $this->getID(); // an integer number
        if ($name === 'name')
            return $this->getName(); // a string
        if ($name === 'description')
            return $this->getDescription(); // a string
        if ($name === 'price')
            return $this->getPrice(); // a money amount

        throw new \InvalidArgumentException('Property "'.$name.'" in class "ERP\Product" does not exist and could not be retrieved!');
    }

// ============================================================================

    /**
     * Property existence checker
     *
     * @param string $name Property name to check for existence
     *
     * @return bool will return true if and only if the propery exist and is not null
     */
    public function __isset($name)
    {
        if ($name === 'URI')
            return $this->URI !== null;
        if ($name === 'name')
            return true; // a string (always set)
        if ($name === 'description')
            return true; // a string (always set)
        if ($name === 'price')
            return true; // a money amount (always set)

        return false;
    }

    private static $_read_only_properties = array('URI', 'ID');

    /**
     * @param int $value an integer number
     *
     * @return int
     */
    private function setID($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "ID" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toInteger($value);
        $this->ID = $value;
        return $value;
    }

    /**
     * @param string $value a string
     *
     * @return string
     */
    public function setName($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "name" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toString($value);
        $this->name = $value;
        return $value;
    }

    /**
     * @param string $value a string
     *
     * @return string
     */
    public function setDescription($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "description" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toString($value);
        $this->description = $value;
        return $value;
    }

    /**
     * @param \NGS\Money $value a money amount
     *
     * @return \NGS\Money
     */
    public function setPrice($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "price" cannot be set to null because it is non-nullable!');
        $value = new \NGS\Money($value);
        $this->price = $value;
        return $value;
    }

    /**
     * Property setter which checks for invalid access to entity properties and enforces proper type checks
     *
     * @param string $name Property name
     * @param mixed $value Property value
     */
    public function __set($name, $value)
    {
        if(in_array($name, self::$_read_only_properties, true))
            throw new \LogicException('Property "'.$name.'" in "ERP\Product" cannot be set, because it is read-only!');
        if ($name === 'name')
            return $this->setName($value); // a string
        if ($name === 'description')
            return $this->setDescription($value); // a string
        if ($name === 'price')
            return $this->setPrice($value); // a money amount
        throw new \InvalidArgumentException('Property "'.$name.'" in class "ERP\Product" does not exist and could not be set!');
    }

    /**
     * Will unset a property if it exists, but throw an exception if it is not nullable
     *
     * @param string $name Property name to unset (set to null)
     */
    public function __unset($name)
    {
        if(in_array($name, self::$_read_only_properties, true))
            throw new \LogicException('Property "'.$name.'" cannot be unset, because it is read-only!');
        if ($name === 'name')
            throw new \LogicException('The property "name" cannot be unset because it is non-nullable!'); // a string (cannot be unset)
        if ($name === 'description')
            throw new \LogicException('The property "description" cannot be unset because it is non-nullable!'); // a string (cannot be unset)
        if ($name === 'price')
            throw new \LogicException('The property "price" cannot be unset because it is non-nullable!'); // a money amount (cannot be unset)
    }

    /**
     * Create or update ERP\Product instance (server call)
     *
     * @return modified instance object
     */
    public function persist()
    {

        $newObject = parent::persist();
        $this->updateWithAnother($newObject);

        return $this;
    }

    private function updateWithAnother(\ERP\Product $result)
    {
        $this->URI = $result->URI;

        $this->name = $result->name;
        $this->description = $result->description;
        $this->price = $result->price;
        $this->ID = $result->ID;
    }

    public function toJson()
    {
        return \ERP\ProductJsonConverter::toJson($this);
    }

    public static function fromJson($item)
    {
        return \ERP\ProductJsonConverter::fromJson($item);
    }

    public function __toString()
    {
        return 'ERP\Product'.$this->toJson();
    }

    public function __clone()
    {
        return \ERP\ProductArrayConverter::fromArray(\ERP\ProductArrayConverter::toArray($this));
    }

    public function toArray()
    {
        return \ERP\ProductArrayConverter::toArray($this);
    }

    /**
     * Implementation of the IteratorAggregate interface via \ArrayIterator
     *
     * @return Traversable a new iterator specially created for this iteratation
     */
    public function getIterator()
    {
        return new \ArrayIterator(\ERP\ProductArrayConverter::toArray($this));
    }
}