<?php
namespace Store;

require_once __DIR__.'/InvoiceJsonConverter.php';
require_once __DIR__.'/InvoiceArrayConverter.php';

/**
 * Generated from NGS DSL
 *
 * @property string $URI a unique object identifier (read-only)
 * @property int $ID autogenerated by server (read-only)
 * @property int $year an integer number
 * @property string $number a string
 * @property \NGS\LocalDate $paid a date, can be null
 * @property string $code a string
 *
 * @package Store
 * @version 0.9.9 beta
 */
class Invoice extends \NGS\Patterns\AggregateRoot implements \IteratorAggregate
{
    protected $URI;
    protected $ID;
    protected $year;
    protected $number;
    protected $paid;
    protected $code;

    /**
     * Constructs object using a key-property array or instance of class "Store\Invoice"
     *
     * @param array|void $data key-property array or instance of class "Store\Invoice" or pass void to provide all fields with defaults
     */
    public function __construct($data = array(), $construction_type = '')
    {
        if(is_array($data) && $construction_type !== 'build_internal') {
            foreach($data as $key => $val) {
                if(in_array($key, self::$_read_only_properties, true))
                    throw new \LogicException($key.' is a read only property and can\'t be set through the constructor.');
            }
        }
        if (is_array($data)) {
            $this->fromArray($data);
        } else {
            throw new \InvalidArgumentException('Constructor parameter must be an array! Type was: '.\NGS\Utils::getType($data));
        }
    }

    /**
     * Supply default values for uninitialized properties
     *
     * @param array $data key-property array which will be filled in-place
     */
    private static function provideDefaults(array &$data)
    {
        if(!array_key_exists('URI', $data))
            $data['URI'] = null; //a string representing a unique object identifier
        if(!array_key_exists('ID', $data))
            $data['ID'] = 0; // an integer number
        if(!array_key_exists('year', $data))
            $data['year'] = 0; // an integer number
        if(!array_key_exists('number', $data))
            $data['number'] = ''; // a string
        if(!array_key_exists('code', $data))
            $data['code'] = ''; // a string
    }

    /**
     * Constructs object from a key-property array
     *
     * @param array $data key-property array
     */
    private function fromArray(array $data)
    {
        $this->provideDefaults($data);

        if(isset($data['URI']))
            $this->URI = \NGS\Converter\PrimitiveConverter::toString($data['URI']);
        unset($data['URI']);
        if (array_key_exists('ID', $data))
            $this->setID($data['ID']);
        unset($data['ID']);
        if (array_key_exists('year', $data))
            $this->setYear($data['year']);
        unset($data['year']);
        if (array_key_exists('number', $data))
            $this->setNumber($data['number']);
        unset($data['number']);
        if (array_key_exists('paid', $data))
            $this->setPaid($data['paid']);
        unset($data['paid']);
        if (array_key_exists('code', $data))
            $this->setCode($data['code']);
        unset($data['code']);

        if (count($data) !== 0 && \NGS\Utils::WarningsAsErrors())
            throw new \InvalidArgumentException('Superflous array keys found in "Store\Invoice" constructor: '.implode(', ', array_keys($data)));
    }

// ============================================================================

    /**
     * Helper getter function, body for magic method $this->__get('URI')
     * URI is a string representation of the primary key.
     *
     * @return string unique resource identifier representing this object
     */
    public function getURI()
    {
        return $this->URI;
    }

    /**
     * @return an integer number
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * @return an integer number
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * @return a string
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * @return a date, can be null
     */
    public function getPaid()
    {
        return $this->paid;
    }

    /**
     * @return a string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Property getter which throws Exceptions on invalid access
     *
     * @param string $name Property name
     *
     * @return mixed
     */
    public function __get($name)
    {
        if ($name === 'URI')
            return $this->getURI(); // a string representing a unique object identifier
        if ($name === 'ID')
            return $this->getID(); // an integer number
        if ($name === 'year')
            return $this->getYear(); // an integer number
        if ($name === 'number')
            return $this->getNumber(); // a string
        if ($name === 'paid')
            return $this->getPaid(); // a date, can be null
        if ($name === 'code')
            return $this->getCode(); // a string

        throw new \InvalidArgumentException('Property "'.$name.'" in class "Store\Invoice" does not exist and could not be retrieved!');
    }

// ============================================================================

    /**
     * Property existence checker
     *
     * @param string $name Property name to check for existence
     *
     * @return bool will return true if and only if the propery exist and is not null
     */
    public function __isset($name)
    {
        if ($name === 'URI')
            return $this->URI !== null;
        if ($name === 'year')
            return true; // an integer number (always set)
        if ($name === 'number')
            return true; // a string (always set)
        if ($name === 'paid')
            return $this->getPaid() !== null; // a date, can be null
        if ($name === 'code')
            return true; // a string (always set)

        return false;
    }

    private static $_read_only_properties = array('URI', 'ID');

    /**
     * @param int $value an integer number
     *
     * @return int
     */
    private function setID($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "ID" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toInteger($value);
        $this->ID = $value;
        return $value;
    }

    /**
     * @param int $value an integer number
     *
     * @return int
     */
    public function setYear($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "year" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toInteger($value);
        $this->year = $value;
        return $value;
    }

    /**
     * @param string $value a string
     *
     * @return string
     */
    public function setNumber($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "number" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toString($value);
        $this->number = $value;
        return $value;
    }

    /**
     * @param \NGS\LocalDate $value a date, can be null
     *
     * @return \NGS\LocalDate
     */
    public function setPaid($value)
    {
        $value = $value !== null ? new \NGS\LocalDate($value) : null;
        $this->paid = $value;
        return $value;
    }

    /**
     * @param string $value a string
     *
     * @return string
     */
    public function setCode($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "code" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toString($value);
        $this->code = $value;
        return $value;
    }

    /**
     * Property setter which checks for invalid access to entity properties and enforces proper type checks
     *
     * @param string $name Property name
     * @param mixed $value Property value
     */
    public function __set($name, $value)
    {
        if(in_array($name, self::$_read_only_properties, true))
            throw new \LogicException('Property "'.$name.'" in "Store\Invoice" cannot be set, because it is read-only!');
        if ($name === 'year')
            return $this->setYear($value); // an integer number
        if ($name === 'number')
            return $this->setNumber($value); // a string
        if ($name === 'paid')
            return $this->setPaid($value); // a date, can be null
        if ($name === 'code')
            return $this->setCode($value); // a string
        throw new \InvalidArgumentException('Property "'.$name.'" in class "Store\Invoice" does not exist and could not be set!');
    }

    /**
     * Will unset a property if it exists, but throw an exception if it is not nullable
     *
     * @param string $name Property name to unset (set to null)
     */
    public function __unset($name)
    {
        if(in_array($name, self::$_read_only_properties, true))
            throw new \LogicException('Property "'.$name.'" cannot be unset, because it is read-only!');
        if ($name === 'year')
            throw new \LogicException('The property "year" cannot be unset because it is non-nullable!'); // an integer number (cannot be unset)
        if ($name === 'number')
            throw new \LogicException('The property "number" cannot be unset because it is non-nullable!'); // a string (cannot be unset)
        if ($name === 'paid')
            $this->setPaid(null);; // a date, can be null
        if ($name === 'code')
            throw new \LogicException('The property "code" cannot be unset because it is non-nullable!'); // a string (cannot be unset)
    }

    /**
     * Create or update Store\Invoice instance (server call)
     *
     * @return modified instance object
     */
    public function persist()
    {

        $newObject = parent::persist();
        $this->updateWithAnother($newObject);

        return $this;
    }

    private function updateWithAnother(\Store\Invoice $result)
    {
        $this->URI = $result->URI;

        $this->year = $result->year;
        $this->number = $result->number;
        $this->paid = $result->paid;
        $this->code = $result->code;
        $this->ID = $result->ID;
    }

    public function toJson()
    {
        return \Store\InvoiceJsonConverter::toJson($this);
    }

    public static function fromJson($item)
    {
        return \Store\InvoiceJsonConverter::fromJson($item);
    }

    public function __toString()
    {
        return 'Store\Invoice'.$this->toJson();
    }

    public function __clone()
    {
        return \Store\InvoiceArrayConverter::fromArray(\Store\InvoiceArrayConverter::toArray($this));
    }

    public function toArray()
    {
        return \Store\InvoiceArrayConverter::toArray($this);
    }

    /**
     * Implementation of the IteratorAggregate interface via \ArrayIterator
     *
     * @return Traversable a new iterator specially created for this iteratation
     */
    public function getIterator()
    {
        return new \ArrayIterator(\Store\InvoiceArrayConverter::toArray($this));
    }

    /**
     * Find data using declared specification notPaid
     * Search can be limited by $searchLimit and $searchOffset integer arguments
     *
     * @return array of objects that satisfy specification
     */
    public static function notPaid($searchLimit = null, $searchOffset = null)
    {
        require_once __DIR__.'/Invoice/notPaid.php';
        $specification = new \Store\Invoice\notPaid();
        return $specification->search($searchLimit, $searchOffset);
    }
}