<?php
namespace Cinema;

require_once __DIR__.'/MovieJsonConverter.php';
require_once __DIR__.'/MovieArrayConverter.php';

/**
 * Generated from NGS DSL
 *
 * @property string $URI a unique object identifier (read-only)
 * @property int $ID autogenerated by server (read-only)
 * @property string $title a string
 * @property string $shortTitle a string of length 10
 * @property int $year an integer number
 * @property int $durationSeconds an integer number
 * @property float $violenceFactor a floating point number
 * @property float $loudnessIndex a floating point number
 * @property bool $under18 a boolean value
 * @property array $awards a map[string, string]
 * @property \NGS\ByteStream $poster a byte stream
 * @property \NGS\LocalDate $released a date
 * @property \NGS\Timestamp $premiered a timestamp with time zone
 * @property \NGS\BigDecimal $criticsRating a decimal
 * @property \NGS\BigDecimal $publicRating a decimal with scale of 4
 * @property \NGS\UUID $catalogId a uuid
 * @property \NGS\Money $budget a money amount
 * @property SimpleXMLElement $captions a xml value
 *
 * @package Cinema
 * @version 0.9.9 beta
 */
class Movie extends \NGS\Patterns\AggregateRoot implements \IteratorAggregate
{
    protected $URI;
    protected $ID;
    protected $title;
    protected $shortTitle;
    protected $year;
    protected $durationSeconds;
    protected $violenceFactor;
    protected $loudnessIndex;
    protected $under18;
    protected $awards;
    protected $poster;
    protected $released;
    protected $premiered;
    protected $criticsRating;
    protected $publicRating;
    protected $catalogId;
    protected $budget;
    protected $captions;

    /**
     * Constructs object using a key-property array or instance of class "Cinema\Movie"
     *
     * @param array|void $data key-property array or instance of class "Cinema\Movie" or pass void to provide all fields with defaults
     */
    public function __construct($data = array(), $construction_type = '')
    {
        if(is_array($data) && $construction_type !== 'build_internal') {
            foreach($data as $key => $val) {
                if(in_array($key, self::$_read_only_properties, true))
                    throw new \LogicException($key.' is a read only property and can\'t be set through the constructor.');
            }
        }
        if (is_array($data)) {
            $this->fromArray($data);
        } else {
            throw new \InvalidArgumentException('Constructor parameter must be an array! Type was: '.\NGS\Utils::getType($data));
        }
    }

    /**
     * Supply default values for uninitialized properties
     *
     * @param array $data key-property array which will be filled in-place
     */
    private static function provideDefaults(array &$data)
    {
        if(!array_key_exists('URI', $data))
            $data['URI'] = null; //a string representing a unique object identifier
        if(!array_key_exists('ID', $data))
            $data['ID'] = 0; // an integer number
        if(!array_key_exists('title', $data))
            $data['title'] = ''; // a string
        if(!array_key_exists('shortTitle', $data))
            $data['shortTitle'] = ''; // a string of length 10
        if(!array_key_exists('year', $data))
            $data['year'] = 0; // an integer number
        if(!array_key_exists('durationSeconds', $data))
            $data['durationSeconds'] = 0; // an integer number
        if(!array_key_exists('violenceFactor', $data))
            $data['violenceFactor'] = 0.; // a floating point number
        if(!array_key_exists('loudnessIndex', $data))
            $data['loudnessIndex'] = 0.; // a floating point number
        if(!array_key_exists('under18', $data))
            $data['under18'] = false; // a boolean value
        if(!array_key_exists('awards', $data))
            $data['awards'] = array(); // a map[string, string]
        if(!array_key_exists('poster', $data))
            $data['poster'] = new \NGS\ByteStream(); // a byte stream
        if(!array_key_exists('released', $data))
            $data['released'] = new \NGS\LocalDate(); // a date
        if(!array_key_exists('premiered', $data))
            $data['premiered'] = new \NGS\Timestamp(); // a timestamp with time zone
        if(!array_key_exists('criticsRating', $data))
            $data['criticsRating'] = new \NGS\BigDecimal(0); // a decimal
        if(!array_key_exists('publicRating', $data))
            $data['publicRating'] = new \NGS\BigDecimal(0, 4); // a decimal with scale of 4
        if(!array_key_exists('catalogId', $data))
            $data['catalogId'] = new \NGS\UUID(); // a uuid
        if(!array_key_exists('budget', $data))
            $data['budget'] = new \NGS\Money(0); // a money amount
    }

    /**
     * Constructs object from a key-property array
     *
     * @param array $data key-property array
     */
    private function fromArray(array $data)
    {
        $this->provideDefaults($data);

        if(isset($data['URI']))
            $this->URI = \NGS\Converter\PrimitiveConverter::toString($data['URI']);
        unset($data['URI']);
        if (array_key_exists('ID', $data))
            $this->setID($data['ID']);
        unset($data['ID']);
        if (array_key_exists('title', $data))
            $this->setTitle($data['title']);
        unset($data['title']);
        if (array_key_exists('shortTitle', $data))
            $this->setShortTitle($data['shortTitle']);
        unset($data['shortTitle']);
        if (array_key_exists('year', $data))
            $this->setYear($data['year']);
        unset($data['year']);
        if (array_key_exists('durationSeconds', $data))
            $this->setDurationSeconds($data['durationSeconds']);
        unset($data['durationSeconds']);
        if (array_key_exists('violenceFactor', $data))
            $this->setViolenceFactor($data['violenceFactor']);
        unset($data['violenceFactor']);
        if (array_key_exists('loudnessIndex', $data))
            $this->setLoudnessIndex($data['loudnessIndex']);
        unset($data['loudnessIndex']);
        if (array_key_exists('under18', $data))
            $this->setUnder18($data['under18']);
        unset($data['under18']);
        if (array_key_exists('awards', $data))
            $this->setAwards($data['awards']);
        unset($data['awards']);
        if (array_key_exists('poster', $data))
            $this->setPoster($data['poster']);
        unset($data['poster']);
        if (array_key_exists('released', $data))
            $this->setReleased($data['released']);
        unset($data['released']);
        if (array_key_exists('premiered', $data))
            $this->setPremiered($data['premiered']);
        unset($data['premiered']);
        if (array_key_exists('criticsRating', $data))
            $this->setCriticsRating($data['criticsRating']);
        unset($data['criticsRating']);
        if (array_key_exists('publicRating', $data))
            $this->setPublicRating($data['publicRating']);
        unset($data['publicRating']);
        if (array_key_exists('catalogId', $data))
            $this->setCatalogId($data['catalogId']);
        unset($data['catalogId']);
        if (array_key_exists('budget', $data))
            $this->setBudget($data['budget']);
        unset($data['budget']);
        if (array_key_exists('captions', $data))
            $this->setCaptions($data['captions']);
        unset($data['captions']);

        if (count($data) !== 0 && \NGS\Utils::WarningsAsErrors())
            throw new \InvalidArgumentException('Superflous array keys found in "Cinema\Movie" constructor: '.implode(', ', array_keys($data)));
    }

// ============================================================================

    /**
     * Helper getter function, body for magic method $this->__get('URI')
     * URI is a string representation of the primary key.
     *
     * @return string unique resource identifier representing this object
     */
    public function getURI()
    {
        return $this->URI;
    }

    /**
     * @return an integer number
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * @return a string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @return a string of length 10
     */
    public function getShortTitle()
    {
        return $this->shortTitle;
    }

    /**
     * @return an integer number
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * @return an integer number
     */
    public function getDurationSeconds()
    {
        return $this->durationSeconds;
    }

    /**
     * @return a floating point number
     */
    public function getViolenceFactor()
    {
        return $this->violenceFactor;
    }

    /**
     * @return a floating point number
     */
    public function getLoudnessIndex()
    {
        return $this->loudnessIndex;
    }

    /**
     * @return a boolean value
     */
    public function getUnder18()
    {
        return $this->under18;
    }

    /**
     * @return a map[string, string]
     */
    public function getAwards()
    {
        return $this->awards;
    }

    /**
     * @return a byte stream
     */
    public function getPoster()
    {
        return $this->poster;
    }

    /**
     * @return a date
     */
    public function getReleased()
    {
        return $this->released;
    }

    /**
     * @return a timestamp with time zone
     */
    public function getPremiered()
    {
        return $this->premiered;
    }

    /**
     * @return a decimal
     */
    public function getCriticsRating()
    {
        return $this->criticsRating;
    }

    /**
     * @return a decimal with scale of 4
     */
    public function getPublicRating()
    {
        return $this->publicRating;
    }

    /**
     * @return a uuid
     */
    public function getCatalogId()
    {
        return $this->catalogId;
    }

    /**
     * @return a money amount
     */
    public function getBudget()
    {
        return $this->budget;
    }

    /**
     * @return a xml value
     */
    public function getCaptions()
    {
        return $this->captions;
    }

    /**
     * Property getter which throws Exceptions on invalid access
     *
     * @param string $name Property name
     *
     * @return mixed
     */
    public function __get($name)
    {
        if ($name === 'URI')
            return $this->getURI(); // a string representing a unique object identifier
        if ($name === 'ID')
            return $this->getID(); // an integer number
        if ($name === 'title')
            return $this->getTitle(); // a string
        if ($name === 'shortTitle')
            return $this->getShortTitle(); // a string of length 10
        if ($name === 'year')
            return $this->getYear(); // an integer number
        if ($name === 'durationSeconds')
            return $this->getDurationSeconds(); // an integer number
        if ($name === 'violenceFactor')
            return $this->getViolenceFactor(); // a floating point number
        if ($name === 'loudnessIndex')
            return $this->getLoudnessIndex(); // a floating point number
        if ($name === 'under18')
            return $this->getUnder18(); // a boolean value
        if ($name === 'awards')
            return $this->getAwards(); // a map[string, string]
        if ($name === 'poster')
            return $this->getPoster(); // a byte stream
        if ($name === 'released')
            return $this->getReleased(); // a date
        if ($name === 'premiered')
            return $this->getPremiered(); // a timestamp with time zone
        if ($name === 'criticsRating')
            return $this->getCriticsRating(); // a decimal
        if ($name === 'publicRating')
            return $this->getPublicRating(); // a decimal with scale of 4
        if ($name === 'catalogId')
            return $this->getCatalogId(); // a uuid
        if ($name === 'budget')
            return $this->getBudget(); // a money amount
        if ($name === 'captions')
            return $this->getCaptions(); // a xml value

        throw new \InvalidArgumentException('Property "'.$name.'" in class "Cinema\Movie" does not exist and could not be retrieved!');
    }

// ============================================================================

    /**
     * Property existence checker
     *
     * @param string $name Property name to check for existence
     *
     * @return bool will return true if and only if the propery exist and is not null
     */
    public function __isset($name)
    {
        if ($name === 'URI')
            return $this->URI !== null;
        if ($name === 'title')
            return true; // a string (always set)
        if ($name === 'shortTitle')
            return true; // a string of length 10 (always set)
        if ($name === 'year')
            return true; // an integer number (always set)
        if ($name === 'durationSeconds')
            return true; // an integer number (always set)
        if ($name === 'violenceFactor')
            return true; // a floating point number (always set)
        if ($name === 'loudnessIndex')
            return true; // a floating point number (always set)
        if ($name === 'under18')
            return true; // a boolean value (always set)
        if ($name === 'awards')
            return true; // a map[string, string] (always set)
        if ($name === 'poster')
            return true; // a byte stream (always set)
        if ($name === 'released')
            return true; // a date (always set)
        if ($name === 'premiered')
            return true; // a timestamp with time zone (always set)
        if ($name === 'criticsRating')
            return true; // a decimal (always set)
        if ($name === 'publicRating')
            return true; // a decimal with scale of 4 (always set)
        if ($name === 'catalogId')
            return true; // a uuid (always set)
        if ($name === 'budget')
            return true; // a money amount (always set)
        if ($name === 'captions')
            return true; // a xml value (always set)

        return false;
    }

    private static $_read_only_properties = array('URI', 'ID');

    /**
     * @param int $value an integer number
     *
     * @return int
     */
    private function setID($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "ID" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toInteger($value);
        $this->ID = $value;
        return $value;
    }

    /**
     * @param string $value a string
     *
     * @return string
     */
    public function setTitle($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "title" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toString($value);
        $this->title = $value;
        return $value;
    }

    /**
     * @param string $value a string of length 10
     *
     * @return string
     */
    public function setShortTitle($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "shortTitle" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toFixedString($value, 10);
        $this->shortTitle = $value;
        return $value;
    }

    /**
     * @param int $value an integer number
     *
     * @return int
     */
    public function setYear($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "year" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toInteger($value);
        $this->year = $value;
        return $value;
    }

    /**
     * @param int $value an integer number
     *
     * @return int
     */
    public function setDurationSeconds($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "durationSeconds" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toInteger($value);
        $this->durationSeconds = $value;
        return $value;
    }

    /**
     * @param float $value a floating point number
     *
     * @return float
     */
    public function setViolenceFactor($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "violenceFactor" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toFloat($value);
        $this->violenceFactor = $value;
        return $value;
    }

    /**
     * @param float $value a floating point number
     *
     * @return float
     */
    public function setLoudnessIndex($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "loudnessIndex" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toFloat($value);
        $this->loudnessIndex = $value;
        return $value;
    }

    /**
     * @param bool $value a boolean value
     *
     * @return bool
     */
    public function setUnder18($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "under18" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toBoolean($value);
        $this->under18 = $value;
        return $value;
    }

    /**
     * @param array $value a map[string, string]
     *
     * @return array
     */
    public function setAwards($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "awards" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\PrimitiveConverter::toMap($value);
        $this->awards = $value;
        return $value;
    }

    /**
     * @param \NGS\ByteStream $value a byte stream
     *
     * @return \NGS\ByteStream
     */
    public function setPoster($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "poster" cannot be set to null because it is non-nullable!');
        $value = \NGS\ByteStream::fromBase64($value);
        $this->poster = $value;
        return $value;
    }

    /**
     * @param \NGS\LocalDate $value a date
     *
     * @return \NGS\LocalDate
     */
    public function setReleased($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "released" cannot be set to null because it is non-nullable!');
        $value = new \NGS\LocalDate($value);
        $this->released = $value;
        return $value;
    }

    /**
     * @param \NGS\Timestamp $value a timestamp with time zone
     *
     * @return \NGS\Timestamp
     */
    public function setPremiered($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "premiered" cannot be set to null because it is non-nullable!');
        $value = new \NGS\Timestamp($value);
        $this->premiered = $value;
        return $value;
    }

    /**
     * @param \NGS\BigDecimal $value a decimal
     *
     * @return \NGS\BigDecimal
     */
    public function setCriticsRating($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "criticsRating" cannot be set to null because it is non-nullable!');
        $value = new \NGS\BigDecimal($value);
        $this->criticsRating = $value;
        return $value;
    }

    /**
     * @param \NGS\BigDecimal $value a decimal with scale of 4
     *
     * @return \NGS\BigDecimal
     */
    public function setPublicRating($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "publicRating" cannot be set to null because it is non-nullable!');
        $value = new \NGS\BigDecimal($value, 4);
        $this->publicRating = $value;
        return $value;
    }

    /**
     * @param \NGS\UUID $value a uuid
     *
     * @return \NGS\UUID
     */
    public function setCatalogId($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "catalogId" cannot be set to null because it is non-nullable!');
        $value = new \NGS\UUID($value);
        $this->catalogId = $value;
        return $value;
    }

    /**
     * @param \NGS\Money $value a money amount
     *
     * @return \NGS\Money
     */
    public function setBudget($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "budget" cannot be set to null because it is non-nullable!');
        $value = new \NGS\Money($value);
        $this->budget = $value;
        return $value;
    }

    /**
     * @param SimpleXMLElement $value a xml value
     *
     * @return SimpleXMLElement
     */
    public function setCaptions($value)
    {
        if ($value === null)
            throw new \InvalidArgumentException('Property "captions" cannot be set to null because it is non-nullable!');
        $value = \NGS\Converter\XmlConverter::toXml($value);
        $this->captions = $value;
        return $value;
    }

    /**
     * Property setter which checks for invalid access to entity properties and enforces proper type checks
     *
     * @param string $name Property name
     * @param mixed $value Property value
     */
    public function __set($name, $value)
    {
        if(in_array($name, self::$_read_only_properties, true))
            throw new \LogicException('Property "'.$name.'" in "Cinema\Movie" cannot be set, because it is read-only!');
        if ($name === 'title')
            return $this->setTitle($value); // a string
        if ($name === 'shortTitle')
            return $this->setShortTitle($value); // a string of length 10
        if ($name === 'year')
            return $this->setYear($value); // an integer number
        if ($name === 'durationSeconds')
            return $this->setDurationSeconds($value); // an integer number
        if ($name === 'violenceFactor')
            return $this->setViolenceFactor($value); // a floating point number
        if ($name === 'loudnessIndex')
            return $this->setLoudnessIndex($value); // a floating point number
        if ($name === 'under18')
            return $this->setUnder18($value); // a boolean value
        if ($name === 'awards')
            return $this->setAwards($value); // a map[string, string]
        if ($name === 'poster')
            return $this->setPoster($value); // a byte stream
        if ($name === 'released')
            return $this->setReleased($value); // a date
        if ($name === 'premiered')
            return $this->setPremiered($value); // a timestamp with time zone
        if ($name === 'criticsRating')
            return $this->setCriticsRating($value); // a decimal
        if ($name === 'publicRating')
            return $this->setPublicRating($value); // a decimal with scale of 4
        if ($name === 'catalogId')
            return $this->setCatalogId($value); // a uuid
        if ($name === 'budget')
            return $this->setBudget($value); // a money amount
        if ($name === 'captions')
            return $this->setCaptions($value); // a xml value
        throw new \InvalidArgumentException('Property "'.$name.'" in class "Cinema\Movie" does not exist and could not be set!');
    }

    /**
     * Will unset a property if it exists, but throw an exception if it is not nullable
     *
     * @param string $name Property name to unset (set to null)
     */
    public function __unset($name)
    {
        if(in_array($name, self::$_read_only_properties, true))
            throw new \LogicException('Property "'.$name.'" cannot be unset, because it is read-only!');
        if ($name === 'title')
            throw new \LogicException('The property "title" cannot be unset because it is non-nullable!'); // a string (cannot be unset)
        if ($name === 'shortTitle')
            throw new \LogicException('The property "shortTitle" cannot be unset because it is non-nullable!'); // a string of length 10 (cannot be unset)
        if ($name === 'year')
            throw new \LogicException('The property "year" cannot be unset because it is non-nullable!'); // an integer number (cannot be unset)
        if ($name === 'durationSeconds')
            throw new \LogicException('The property "durationSeconds" cannot be unset because it is non-nullable!'); // an integer number (cannot be unset)
        if ($name === 'violenceFactor')
            throw new \LogicException('The property "violenceFactor" cannot be unset because it is non-nullable!'); // a floating point number (cannot be unset)
        if ($name === 'loudnessIndex')
            throw new \LogicException('The property "loudnessIndex" cannot be unset because it is non-nullable!'); // a floating point number (cannot be unset)
        if ($name === 'under18')
            throw new \LogicException('The property "under18" cannot be unset because it is non-nullable!'); // a boolean value (cannot be unset)
        if ($name === 'awards')
            throw new \LogicException('The property "awards" cannot be unset because it is non-nullable!'); // a map[string, string] (cannot be unset)
        if ($name === 'poster')
            throw new \LogicException('The property "poster" cannot be unset because it is non-nullable!'); // a byte stream (cannot be unset)
        if ($name === 'released')
            throw new \LogicException('The property "released" cannot be unset because it is non-nullable!'); // a date (cannot be unset)
        if ($name === 'premiered')
            throw new \LogicException('The property "premiered" cannot be unset because it is non-nullable!'); // a timestamp with time zone (cannot be unset)
        if ($name === 'criticsRating')
            throw new \LogicException('The property "criticsRating" cannot be unset because it is non-nullable!'); // a decimal (cannot be unset)
        if ($name === 'publicRating')
            throw new \LogicException('The property "publicRating" cannot be unset because it is non-nullable!'); // a decimal with scale of 4 (cannot be unset)
        if ($name === 'catalogId')
            throw new \LogicException('The property "catalogId" cannot be unset because it is non-nullable!'); // a uuid (cannot be unset)
        if ($name === 'budget')
            throw new \LogicException('The property "budget" cannot be unset because it is non-nullable!'); // a money amount (cannot be unset)
        if ($name === 'captions')
            throw new \LogicException('The property "captions" cannot be unset because it is non-nullable!'); // a xml value (cannot be unset)
    }

    /**
     * Create or update Cinema\Movie instance (server call)
     *
     * @return modified instance object
     */
    public function persist()
    {

        $newObject = parent::persist();
        $this->updateWithAnother($newObject);

        return $this;
    }

    private function updateWithAnother(\Cinema\Movie $result)
    {
        $this->URI = $result->URI;

        $this->title = $result->title;
        $this->shortTitle = $result->shortTitle;
        $this->year = $result->year;
        $this->durationSeconds = $result->durationSeconds;
        $this->violenceFactor = $result->violenceFactor;
        $this->loudnessIndex = $result->loudnessIndex;
        $this->under18 = $result->under18;
        $this->awards = $result->awards;
        $this->poster = $result->poster;
        $this->released = $result->released;
        $this->premiered = $result->premiered;
        $this->criticsRating = $result->criticsRating;
        $this->publicRating = $result->publicRating;
        $this->catalogId = $result->catalogId;
        $this->budget = $result->budget;
        $this->captions = $result->captions;
        $this->ID = $result->ID;
    }

    public function toJson()
    {
        return \Cinema\MovieJsonConverter::toJson($this);
    }

    public static function fromJson($item)
    {
        return \Cinema\MovieJsonConverter::fromJson($item);
    }

    public function __toString()
    {
        return 'Cinema\Movie'.$this->toJson();
    }

    public function __clone()
    {
        return \Cinema\MovieArrayConverter::fromArray(\Cinema\MovieArrayConverter::toArray($this));
    }

    public function toArray()
    {
        return \Cinema\MovieArrayConverter::toArray($this);
    }

    /**
     * Implementation of the IteratorAggregate interface via \ArrayIterator
     *
     * @return Traversable a new iterator specially created for this iteratation
     */
    public function getIterator()
    {
        return new \ArrayIterator(\Cinema\MovieArrayConverter::toArray($this));
    }
}